### ISSUE TITLE
Documentation nodes not recognized

### ISSUE THREAD

**Issue by HeRoSofty** [MvRens/x2xmldatabinding#6]
This solution of merge request #4 ignores **every** documentation.
`SchemaItem.Documentation` is a collection of documentation nodes, therefore it **never** `IsTextElement`.
You have to check the collection items, i.e. `SchemaItem.Documentation[0].IsTextElement`

**Comment by MvRens** [comment]
Thanks for reporting! I don't have a Delphi license anymore myself, but if you are willing to make a pull request I'd be happy to merge it.
